data_directory: ../data/processed/
data_name: dataRNA.csv
target_name: class
stop_features: 10000

# RandomForest parameters
n_estimators: 100
model_name: "RandomForest"

# crossValidation
k_fold: 5
repeat: 10

#FeatureSelection
n_features: 5
filter: "Mrmr"

#File
name_each_result: "Result.csv"
name_file_k_fold: "MeanResultsKFold.csv"
name_file_30_repeat: "10MeanResults.csv"