# Data information
data_directory: ../data/processed/
data_name: dataRNA.csv
target_name: class

# RandomForest parameters
n_estimators: 200
model_name: "RandomForest"

#CrossValidation
k_fold: 5
repeat: 2

#FeatureSelection
n_features: 100
filter: "MDFS"


#Files_name
name_file_30_repeat: "10MeanResults_ReliefF.csv"

#File_Scores_Path
scores_file_Mrmr : "./../reports/csv/10MeanResults_MRMR.csv"
scores_file_ReliefF :  "./../reports/csv/10MeanResults_ReliefF.csv"
scores_file_U-test :  "./../reports/csv/10MeanResults_U-test.csv"

#Figures_Path
figures_path: "./../reports/figures/"

#Mode
mode: score
#mode: visualization