data_directory: ../data/processed/
data_name: dataRNA.csv
target_name: class

# RandomForest parameters
n_estimators: 100
model_name: "RandomForest"

# crossValidation
k_fold: 5
repeat: 10

#FeatureSelection
n_features: 5
filter: "U-test"
#filter: "Mrmr"
#filter: "Mrmr"

#File
name_file_30_repeat: "10MeanResults_U-test.csv.csv"